# Generated by Django 6.1 on 2026-09-11 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.roomtype"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.roomtype"
            ),
        ),
        migrations.AddField(
            model_name="bookingguest",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="bookings.booking",
            ),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["room_type_id", "date"], name="availabilit_room_ty_95500a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(fields=["date"], name="availabilit_date_685a5f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("room_type", "date")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_reference"], name="bookings_booking_4d53ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["guest_id"], name="bookings_guest_i_d264cb_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property_id"], name="bookings_propert_3e789f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room_type_id"], name="bookings_room_ty_fb093b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_date"], name="bookings_check_i_04c000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_out_date"], name="bookings_check_o_afb677_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_status_51373b_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status"], name="bookings_payment_3ea9ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("check_in_date__lt", models.F("check_out_date"))),
                name="check_in_before_checkout",
            ),
        ),
    ]
