# Generated by Django 6.0 on 2026-09-15 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("notifications", "0001_initial"),
        (
            "properties",
            "0002_property_house_rules_property_nearby_attractions_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(db_index=True, max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("new_booking", "New Booking"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("booking_modified", "Booking Modified"),
                            ("payment_received", "Payment Received"),
                            ("check_in_reminder", "Check-in Reminder"),
                            ("check_out_reminder", "Check-out Reminder"),
                            ("new_enquiry", "New Enquiry"),
                            ("property_approved", "Property Approved"),
                            ("property_rejected", "Property Rejected"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("message_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                            ("not_configured", "WhatsApp Not Configured"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "whatsapp_message_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.booking",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_notifications",
                "indexes": [
                    models.Index(
                        fields=["recipient_phone"],
                        name="whatsapp_no_recipie_6de19d_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="whatsapp_no_event_t_859004_idx"
                    ),
                    models.Index(
                        fields=["status"], name="whatsapp_no_status_dcecc8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="whatsapp_no_created_aefb07_idx"
                    ),
                ],
            },
        ),
    ]
