# Generated by Django 6.0 on 2026-09-23 01:09

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.core.models.UserManager()),
            ],
        ),
    ]
