# Generated by Django 6.1 on 2026-09-11 01:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "amenities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "property_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "destinations",
                "indexes": [
                    models.Index(fields=["slug"], name="destination_slug_2ea3e4_idx"),
                    models.Index(
                        fields=["is_published"], name="destination_is_publ_f51566_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("published", "Published"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("cover_photo_url", models.URLField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyAmenity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.amenity",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_amenities",
                "unique_together": {("property", "amenity")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                through="properties.PropertyAmenity",
                to="properties.amenity",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.propertytype",
            ),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("max_adults", models.IntegerField(default=2)),
                ("max_children", models.IntegerField(default=0)),
                ("total_occupancy", models.IntegerField(default=2)),
                ("bed_type", models.CharField(blank=True, max_length=50, null=True)),
                ("number_of_beds", models.IntegerField(default=1)),
                ("total_rooms", models.IntegerField(default=1)),
                (
                    "room_size_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "room_types",
            },
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "weekend_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "extra_guest_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "child_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "service_fee_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.0"), max_digits=5
                    ),
                ),
                ("currency", models.CharField(default="LKR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="properties.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "pricing",
            },
        ),
        migrations.CreateModel(
            name="RoomTypeAmenity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.amenity",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "room_type_amenities",
            },
        ),
        migrations.CreateModel(
            name="RoomTypePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cloudinary_url", models.URLField()),
                ("cloudinary_public_id", models.CharField(max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="properties.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "room_type_photos",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_rates",
                        to="properties.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "seasonal_rates",
            },
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cloudinary_url", models.URLField()),
                ("cloudinary_public_id", models.CharField(max_length=255)),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_photos",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["property_id"], name="property_ph_propert_3fe617_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="property_ph_display_303130_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner_id"], name="properties_owner_i_921947_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["city"], name="properties_city_c34f4f_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status"], name="properties_status_e6008a_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["slug"], name="properties_slug_e22d01_idx"),
        ),
        migrations.AddIndex(
            model_name="roomtype",
            index=models.Index(
                fields=["property_id"], name="room_types_propert_d3bcb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomtype",
            index=models.Index(
                fields=["is_active"], name="room_types_is_acti_1d3969_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricing",
            index=models.Index(
                fields=["room_type_id"], name="pricing_room_ty_cf5b60_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomtypeamenity",
            unique_together={("room_type", "amenity")},
        ),
        migrations.AddIndex(
            model_name="roomtypephoto",
            index=models.Index(
                fields=["room_type_id"], name="room_type_p_room_ty_79053d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonalrate",
            index=models.Index(
                fields=["room_type_id"], name="seasonal_ra_room_ty_3b0b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonalrate",
            index=models.Index(
                fields=["start_date", "end_date"], name="seasonal_ra_start_d_fe72b7_idx"
            ),
        ),
    ]
