# Generated by Django 6.0 on 2026-09-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0002_property_house_rules_property_nearby_attractions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomtype",
            name="bed_type",
        ),
        migrations.RemoveField(
            model_name="roomtype",
            name="room_size_sqm",
        ),
        migrations.AddField(
            model_name="roomtype",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                through="properties.RoomTypeAmenity",
                to="properties.amenity",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="bathroom_type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("en-suite", "En-Suite"),
                    ("shared", "Shared"),
                    ("ensuite_partial", "Ensuite Partial"),
                ],
                default="private",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="bed_configuration",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("double", "Double"),
                    ("queen", "Queen"),
                    ("king", "King"),
                    ("twin", "Twin"),
                    ("bunk", "Bunk"),
                    ("futon", "Futon"),
                    ("mixed", "Mixed"),
                ],
                default="double",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_size_sqft",
            field=models.IntegerField(
                blank=True, help_text="Room size in square feet", null=True
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("bedroom", "Bedroom"),
                    ("living_room", "Living Room"),
                    ("studio", "Studio"),
                    ("suite", "Suite"),
                    ("dormitory", "Dormitory"),
                    ("bungalow", "Bungalow"),
                    ("villa", "Villa"),
                ],
                default="bedroom",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="view_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ocean_view", "Ocean View"),
                    ("mountain_view", "Mountain View"),
                    ("garden_view", "Garden View"),
                    ("city_view", "City View"),
                    ("pool_view", "Pool View"),
                    ("balcony", "Balcony"),
                    ("terrace", "Terrace"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="total_rooms",
            field=models.IntegerField(
                default=1, help_text="Number of identical rooms available for booking"
            ),
        ),
    ]
