# Generated by Django 6.0 on 2026-09-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_remove_roomtype_bed_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
