# Generated by Django 6.0 on 2026-09-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_amenity_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="booking_mode",
            field=models.CharField(
                choices=[
                    ("room_types", "Room types"),
                    ("whole_property", "Whole property"),
                ],
                default="room_types",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="is_property_unit",
            field=models.BooleanField(default=False),
        ),
    ]
