# Generated by Django 6.0 on 2026-09-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_property_cover_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("viewed_on", models.DateField(db_index=True)),
                ("visitor_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_views",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "viewed_on", "visitor_hash"),
                        name="unique_daily_property_view",
                    )
                ],
            },
        ),
    ]
